#!/usr/bin/env python3
"""合成回归语料（测试专用，不参与 Skill 运行）。

原 eval/ 目录已删除。回归真正需要的输入只有两类：几篇结构完整、能跑通 Gate 1/2 的稿子，
以及「够大」与「过小」各一张图。这些都能在运行时生成，没有理由入库：
仓库不再为测试保存语料与二进制素材，改稿时也不会出现「素材还在、判断已变」的错觉。

生成的正文一律是合成演示文本：不主张事实、不引用真实机构数据、不冒充新闻稿。
"""
import base64
import os
import struct
import zlib

# 由真实渲染链验证过的两张 JPEG：940×400（2.35:1 封面，宽度过 COVER_MIN_W）
# 与 900×500（正文图）。两者都高于 render.py 的 600px 分辨率下限、远低于 1MB 体积上限，
# 所以只用它们验证「不报警」的路径；报警路径由 TINY 与负例负责。
_COVER_B64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYeLCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wgARCAGQA6wDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAEFBv/EABkBAQEBAQEBAAAAAAAAAAAAAAABBAYDBf/aAAwDAQACEAMQAAAB5mr9PzilipSiKWVViiVZYpYoKWKlKIpZVWKIqUpYoKWKllUillFKiKUpYolVYqWVSKWKUqIpZVWKJVWKligpYpSoillVYoilKligpYpZViKWUUoilKliiVVxquzl4pYqClilFIpZVliiKUpYqClillUilipSiKUpYqJVWKWUCpYpSiKWVViolVYpYoKlillUillVYqIpSligWWKWVSKWKUqIpSliiVZYpYoKWKlKIpZVXGq7OXiiKlKWKJVWKllUililKIqUpYolVYqWKClilKIqWVViiVVipYoKWKWVSKllVYoilKliiVVillWIpYpSiKUqWKJVWKWKgpYpSiKWVZYolVYpYqClillUxquzl4pYqUoillVYqJVWKWKClipSiKWVVioilKWKClipZVIpZVWKiKUpYolWWKWVSKWKUqIpZVWKJVliligpYpSoillVYoipSligpYpZViKWVViiKlKWKJVXGq7OXilioKWKUUipZVWKIpSlioKWKWVSKlilKIpSpYolVYpZVIqWKUoillWWKJVWKWKCpYpZVIpZVliiKUpYoKlillUilipSiKUpYqJVWKWLSKWKlKIpZVXGq7OXioilKWKJaWKllUililKiKUpYolVYqWKClilKiKWVViiLVipYoKWKWVYillVYoipSliiVVillWIpYpSiKlKWKJVWKWKgpYpSiKllVYoilKWKgpYpZVMars5eKlilKIpZVWKiVViligqWKUoillVYqIpSligqWKWVSKWLZYoilKWKJVlillUilipSiKWVViiVZYpYoKWKlloillVYoipSligpYqWVSKWLVioilKWKJVXGq7OXipYoKWKWVSKllVYoilKligpYpZViKWKUoilKliiVVillWIpYpSiKWVZYolVYpYqClillUillWWKIpSlioKWKWVSKlilKIpSliolVYpZVIqWKUoilFXGq7OXioilKWKCpYpZVIpYpSoilKWKJVlillApYpSoillVYolWWKWKClipZVIpZVWKIqUpYoFWKllUililKIqUpYolVYqWKClilKIqWVViiVVipYoKWKWVYxqu3l4qWKUoillWWKJVWKWKCpYpSiKWVZYoilKWKgpYpZVIpZVliiKUpYqJVWKWVSKWKlKIpZVWKiVViligpYqUoillVYqIpSligqWKWVSKWVVioilKWKJVlxqu3l4qWKClilFiKWVViiKlKWKClillWIpYpSiKlKWKJVWKWVYililKIqWVViiVVilioKWKWVSKllVYoilKligpYpZVIqWKUoilKliiVVili0ipYpSiKWVZcars5eKIpSligWWKWVSKWKlKIpSliiVZYpYoKWKlKIpZVWKJVliligpYqWVSKWVVioilKWKJaWKllUililKiKUpYolVYqWLSKWKUqIpZVWKWVYililKIpZalxquzlopYpSiKWWpYolVYpYqClilKIqWVViiLVilioKWKWVSKllVYoilKWKiVVillUipYpSiKUpYqJVWKWKUqIpSliiVZYpYtIpYpSoillVYolWWKWKClillWMars5eKWKClipRSKWVViiKlKWKClipZVIpYpSiKlKWKJVWKllUililKIqWVViiVVipYpSiKUqWKJVWKWKCpYpSiKWVZYoilKWKCpYpZVIpZVliiKUpYolWXGq7OXiiKUpYqJaWKWVSKWKlKIpSliolVYpYoKlilKIpZVWKiVViligqWKWVSKWVVioilKWKWWoillVYoilKligpYpZViKWKUoilKliiVVillIKWKUoipZVXGq7OWililKIqWWliiVVipYpSiKUpYqJVWKWLSKlilKIpZVWKiVViligqWKWVSKWVVioilKWKJalillUilipSiKUpYolWWKWKClipSiKWVViiVZYpYoKWKllUxquzl4pYoKWKlloillVYqIpSligpYqWVSKWUUqIpSliiVZYpZVWKIpSpYolVYpZViKWKUoilKliiVVilioKWKUoillWWKJVWKWKgpYpZVIpZVliiKUpYqBVxquzl4oilKWKgpYpZVIqWKUoilKlillUillFKiKUpYolWWKWVSKWKUqIpZVWKJVliligpYpSoillVYoipSligpYqWVSKWUUoipSliiVVipZVIpYpSiKllVcars5eKIpSpYolpYpZVIqWKUoilKliiVVili0ipYpSiKWVZYolVYpYoKlillUillWWKIpSligqWKWVSKWKlKIpSliolVYpYtIpYqUoillVYqJVWKWKClipZVMars5eKWKUqIpSliiVVipYoKWKUqIpZVWKItWKligpYpZViKWVViiKUqWKJVWKWVYililKIqUpYolVYpYqClilKIqWVViiKUqWKClillUipYtWKIpSpYolVcars5eKWKCpYpSiKWVVioilKWKCpYpZVIpZVliiKUpYolWWKWVSKWKlKIpZVWKJVliligpYqUoillVYoipSligpYqWVSKWLVioilKWKJVWKllUililKiKWWlxquzl4oilKligpYpZViKWKUoilKliiVVili2IpYpSiKWVZYolVYpYqClillUillWWKIpSlioKWKWVSKlilKIpSliolVYpZVIqWKUoillVYqJVWKWKCpYpZVMars5eKWKUqIpRViiVZYpYoKWKUqIpZVWKIqUpYoKWKllUillVYoipSliiVVipZVIpYpSiKlKWKJVWKligpYpSiKllVYoilKligpYpZVIqWVViiKUqWKJVXGq7OXilioKWKUoillWWKIpSlioKWKWVSKWUlKIpSliolVYpZVIpYqUoillVYqJVWKWKClipSiKWVVioilKWKCpYpZVIpZRSoilKWKJVlillApYpSoillVcars5eKIqUpYoKWKWVYililKIqUpYolVYpZViKWKUoipZVWKJVWKligpYpZaIqWVViiKUqWKClillUipYpSiKUqWKJVWKWLSKlilKIpZVliiVViligqWKWWj/xAAUEAEAAAAAAAAAAAAAAAAAAADA/9oACAEBAAEFAjhn/8QAFBEBAAAAAAAAAAAAAAAAAAAAoP/aAAgBAwEBPwE4f//EABQRAQAAAAAAAAAAAAAAAAAAAKD/2gAIAQIBAT8BOH//xAAUEAEAAAAAAAAAAAAAAAAAAADA/9oACAEBAAY/Ajhn/8QAFBABAAAAAAAAAAAAAAAAAAAAwP/aAAgBAQABPyE4Z//aAAwDAQACAAMAAAAQpA+D+oVqW9A+DUoV+C9AerUsD+C9oWrA8D+qVoW/A8DWoV8C/AUrWsB8C/poQ/C8JUqX8A/C0pU+D8AXqUtC+D8oXqA9C+rUoX+A9KWpU8D+A1qW9A+D/ooB+C9oWrW8B+CVoW/C8BWqVoC/A8pWqB8C/oUrW+B8CXoU/D+B1qXpA/D8ppA+D8oXqA9A+DUoX+A9BWrVoD/A9rWrB8D/AKFaxvwfA16FfwvQVK16AfwvaaAPwvCVqhfAPwlKVvgfQl61KQ/gfal6QPQ/qVah/QPQ1qVfg/QF61uQfg/aKB/gvYFq1PA/gnaFvwPA9qFeQvwfK16Afwv6VK1/Afwl6VPw/AX6lfQPw/KaQ/gfaF61PQ/gVaF/wPQ1qVeg/wAD2takH4P+hWtb0H6NWhX8L0F6tXgP8L2mkL8HylepX0L8FStf4H0JelSsP4H2pekD8PylWpP0D8NSlf4P0BetSkP4H0ihP8D0NalHwP8AAVrWtB8DXoVrC9B+rXoB/C9JWrT8B/CVpW/B8BXqVpC/B8rpD+B9qXpU9D+BVqX9A/DepVqD9A/rWpB+D9oXrU9B+DVoX/A9DWrVoD/A9rpS/B8LXoV/C/B0rX8B/CXpUrD8B/qVpA/D8pXqV9C/DUpX+B9C/pU5D+B9qqD/AAPS1qVfg/QFa1vQfg1aFawvQfq1aA/wPYVq1fA/wlaVuwfA/wChSsL4HyKsfwH2JelT8PwFepfkD8NyleoP0D+tSkP4H0BesTwP4BWpbsDwNahWoL8DyusL0H4tegX8L0FatXwH8JWlasHwH+pWkL4HwJeoT0L4FSpf4D0JalSoPwD2qpf0D+NSlX4P0B+tT0P4PWhesD0P6tWgP8DyNahXwL8BStbwHwJ+hS8LwH6qsPwH+JWlb4PwBepTkL4FyheoD0L6lSgP4D2JalT4P4BWpb0D4P6hWoL0D6usL0H6NWhf8D0FatWwP8D2taoHwL+hSsL4HwJehT8LwFSpegD8LylSoPwD8qpP0D8NSlP4H0JatSwP4DWpakDwP6hWoL0DwNahH4L0BatawH4JWhasLwH6qoXwL+JSlb4HwJ+hTkL4FypegD0L6lSoPwD0JalT4PwBepTkD4NyheoD0D6utTwP4JWhb8DwPahXgL8BStagHwL+hSsLwH4JWhT8LwFapXwL8LylboHwL+qoT0L4FShf4D0JalSoP4D2pakD4PyhWoL0D4NShX4L0BatTgP4L2hasDwP6CoXwL8BStb4HwJehTsLwHypegD8LylSoPwD8JSlb4PwBepSkL4HyhesD0P6mkDwP4hWob0DwNahX4L0B6tagH4L2hasLwH4JWgb8DwFapXwL8FSleoH0L+mhT8L4FSpfwD8L6lS4PwDepSkD4PyhepD0D4NShf4D0NatWwP8D2ta8HwP+ihX4L0BStbwH4J2hSsLwF6pWkL8PyFeoX0L8NSlf4H0JelTkP4H2pekD0P6H//xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAgBAwEBPxCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//xAAWEQEBAQAAAAAAAAAAAAAAAAARABD/2gAIAQIBAT8QZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZxmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZnGZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmb/xAAVEAEBAAAAAAAAAAAAAAAAAAAAEf/aAAgBAQABPxCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI/9k="
_FIG_B64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYeLCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wgARCAH0A4QDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAEFBv/EABkBAQEBAQEBAAAAAAAAAAAAAAABBAYDBf/aAAwDAQACEAMQAAAB5lX0/MVYpRYilFWKWUgpZRSiKlFWKBVipRViiUUpZSClilFIqUVYpZQKllFKJRSpYoFWKUUipZRSllAqWKUoilFligVYpZSUolFKWKBZYpQMdWzl5RSlioFWKUVYolJSllApZSUUilFWKgVYpZRSolFKWKBVipRSKUVYqWUCllFKiKUVYoFlillFKJRSpZQKWKUWIpRVillIKWUUoipSlijGps5cpZRSiKlFWKBVipZVWKJRSllIKWKUUipRVillAqWUUoilKligVYpRViolFKWUCpYpSiKUWWKWVSKWUlKJRSligWWKUUillWWKWUCllJSjGVt5cWWKWUCllJSiKUVYqBVilFWKiUUpZQKlilFIpRVipZQKWUUqJRSligWWKUVYolJSllApYpRYilFWKUWIpZRSiUlKWKBVipRSKUVYpYqMcu3l4qUVYolFKWUgpYpRSKlFWKWVSKllFKJRSpYoFWKUVYqJVWKWUCpZRSiKUWWKBVillJSiUUpZQKlilFWKBZYpZQKWUlKIpSlioFWKUVYoxlbOXKWKlFIpZVWKiUUpZQKlilFIpRVipZQKWUUqIpSligWWKUVYolFKllApYpSoilFWKWVYillFKJSUpYoFWKUWWKJVWKWUgpZRSiKlFWKUDHVs5eUUoipRVigVYqWUUolFKllApYpRZYoFWKWUCpZRSiUUWWKBVilFliiUUpZSClilFIpRZYpZVIpZSUolFKWKgVYpRViolFKWUCllJSiKXGps5cpZQKlilFIpRVipZVIpZRSolFKWKBZYpRViiVZYpZQKWUUqIpRVilFiKWUUolJSligVYqUVYoFWKWUgpZRSiKlFWKUUipZVWKJRSpZQKXGVs5eVViiUUqWKClilKligVYpZVIqWUUoilKligVYpRZYolVYpZSClilKIpRZYpZVIpZSUolFKWKgVYpRViolVYpZQKWKlKIpRVipZVIpZVWKiKXHLs5eKUUillFKiUUpZQKlilFWKBZYpZQKWUlKJRRVilFiKUVYolJSllApYqUVYoFWKWVYillFKJSUpYpRSKlFWKJRSpZQKWUUpYqBVilFIqXGVt5cWWKBVillAqWUUolFKlilFIpRZYolFKWUgpZRSligWWKUUillJSiUUpYqUUilFWKgVYpZQKllFKIpRVipRSKWVViolFKWUCpYpRVigFx1bOXlAqWKUVYoFlillApZSUoilKWKUWIpRViiUlKWUClipSligVYqWVSKWUUolJSligVYqUVYolVYqWUClilKiKUVYpRSKllVYolFKligpYpcamzlyiUUqWKUoilFligVYpZSCllFKIqUVYpRSKUWWKJRSllJSiKUVYqBVillAqWUUolFKWKlFIpRViolFKWUCpZRSligWWKUUillFKiUUpcZWzl5QKWUlKWKClilFiKUVYolJSllApYqUVYoFWKlFIpZRSiUlKWKUUipRViiUUqWUCllFKligVYpRSKllFKJRSpZRSiKUWWKBVillIKWKXHLs5eKBVillIKWUUpYqClilFIqUVYolFKWUgpYpSlioFWKUUipZRSiUUqWKUUilFWKgVYpZQKllFKWKBZYpRSKWVZYolFKWUUqIpRVigWWKXGVt5cqIpRVigWWKWUCllJSligVYqUUilBSolFKWUUoipRVigVYqWUCllFKllApYpRYilFWKJRSpZRSiKUqWKBVilFiKWUUolJSlilFIpQlx1beXioKWKUUilFliiUUpZSUoilFWKgVYpRSKllFKWUClipRSKUVYqJVWKWUCpZRSligWWKUUillFKiUUpZRSoilFWKBZYpZQKWUlKWUBVijGps5cpZSUpYoKWKlFIpRViolFKWUUoipSligVYqUUillFKiUUpYpRYilFWKJVWKllApZRSpYoFWKUWIpZVWKJSUpYpSiKUWWKBVillIKWUUoxlbOXlFKWUgpZRSlioFWKUUipZRSiUUqWKUoilFWKgVYpZQKllFKWKCpYpRSKUWWKJRSllFKiKUVYoFlillApZSUpZQKWKUWIpRViiUlKWKMcuzl4pRViolFKWUUoipRVigVYqWVSKWUUqWUClilFiKUVYolVYqWUUolFKligVYpRYillFKWUgpYpSiKUWWKBVillIKWUUpYqBVilFIqUVYoxqbOXKWKUUipRViiUUqWUUoilKWKgVYpRSKllFKWUCpYpRSKUWWKAUpZRSolFKWKBZYpRSKWUlKJRSllJSiKUVYqBVillApZSUpYoFWKlAx1beXlJSligVYqUUillFKllApYpSoilFWKBVipZRSiUUqWKBVilFiKUVYpZSCllFKIpRZYoFWKWUgpZRSllIKWKUUipRViiUUpZSUolFKWKjGpt5cqWUUoilKWKgVYpZVIqWUUpZQKlilFIpRZYolVYpZRSolFKWKBZYpRSKWUlKWUClipSiKUVYoFlillFKJSUpYoKWKlFIpZVWKiUUpZRSjGVs5cVYqWUCllFKiKUVYoFlilFIpZRSpZQKWKUWIpRViiUlKWUUoipSligVYpRYillFKWUgpYpSiKlFWKBVipZRSiUUpYqBVilFIqUVYpYoxy7OXilFWKiUUpZQKlilFIpRZYoFWKWUlKJRSligWWKUUilCUpZQKWUlKIpRVioFWKWUUolJSligpYqUUilFWKllApZRSoilKWKBVipRVijGVs5cpYoFlillVYolFKligpYpSoilFWKWVYillFKIqUpYoKWKUWIpZVWKWUgpYpSiKlFWKJVWKllFKJRSlioKWKUUipZVWKWUCpYpSiKUqWKAXHVs5eUUoilFligVYpRZYolFKWUCpYpRSKUWWKWUCllJSiUUpYqBVilFIpZSUpZQKWKlFIpRVipRSKWUUqJRSligVYqUUillVYqWUCllFKiKXGpt5cqWUClilFiKUVYpZViKWUUolJSligVYqUVYolFKWUgpZRSiKlFWKBVipZRSiUUqWKClilFIqUVYpZQKllFKIpSpYoFWKUWWKJRSllAqXGVt5eVZYolFKWKgpYpRSKUWWKWVSKWUlKIpSlioFWKUVYqJVWKWUClipSiKUVYqWVSKWUUqJRSligqWKUVYolVYqWUClilKiKUpYoFlillVYoilxy7OXigWWKWUUolJSllAVYpRYilFWKWUgpZRSiKlFWKBVipRViiUUqWUClilFIqUVYpZQKllFKJRSpYoFWKUWIpZRSllAqWKUoilFlilFIpcZWzlxSKUWWKWVSKWUlKJRSlioFWKUVYolJSllApZSUoilFWKlFIpZRSolFKWKBVipRVigVYqWUCllFKiKUVYoFlillVYolJSllApYpRZYoBccbOXBaAFolBVAFUUIUUFAolBaAFUlBVAFUlABaFBaIBVFAUlBVAFCWgBaFCVQBVFACWhQKFCVRQFFCVQBQWiAX/xAAUEAEAAAAAAAAAAAAAAAAAAADA/9oACAEBAAEFAl5//8QAFBEBAAAAAAAAAAAAAAAAAAAAoP/aAAgBAwEBPwFkH//EABQRAQAAAAAAAAAAAAAAAAAAAKD/2gAIAQIBAT8BZB//xAAUEAEAAAAAAAAAAAAAAAAAAADA/9oACAEBAAY/Al5//8QAFBABAAAAAAAAAAAAAAAAAAAAwP/aAAgBAQABPyFef//aAAwDAQACAAMAAAAQ/J0L3IwvSsR/K1J2KzsQvD8J3K0tSuRsC/L0J3uQtT+B1K3JwuTsQ9L2NTsA/L0I1uStRuL1I3L0sTuQ9J2L1ISvQsT/ACNS9rEbErwfC9yNL0rEfws70rEfytSdqkbELw/CdytLUrkfQtydCN7kLU/gdStqVLk7APS9idakrUbg9SkrULk/SNy9CE7kLQ9i9SNr0LE7wNS9iNbkr0fC9yNC0rEb0vSdi9yEPydil7EL0/CdytKUrkbUvydCN6kLU7kfStydLk7ELQ9iNStrULk/QNy9CAfQNi9KE7kLQ/i9SFr0LE/wNS9iFbEr0fA9yNK1rEbwvSdCt6EL07AfytDU7EfytSdrkbUrwdCtyNLU7kbStydCt7UL0/CdStqULk7UPy9CN7kLUbg/b0LU/i9SNq0LE70PS9iNakr0bA9yNC9rEb0vSdityEL07EfytCdqkbErwtqlbUvwfAtylKVrkfQtydCl6EL0/AdStqVLk7QPy9CN6lLUfg/SNq1KF/iti9LE70LQ9iNSlrUbk7yNC9iEb0rUfitSNK07EbwtCditbUr0bANytCQvCtyNLU7kbQtidCt7UL07ANStiVLk7UPi9CNykLU7k9SNi9KE70LQ9iNTELQ/iNSlrUbk/wADQvYhW9K1H4LUjataxG8L0nYrWha9HwP8rQnapG1L8Hy5G1L4HQrchS9OxH8rYnUpO1C5PwjcrS1O5O0DYvQje9C1O4DUrYlWxO8Da1G5L8DQvYjW9K1H4rUjYtOxG9LwnYrW1K9GxL8rQne5G1K4HQrcnS9P4rcnS9OxD8LQnYre1C9PwDcrQle5G1L4vQjctC1O5D0rYnWpO9CwPYjUvLwPYjUtK1G4L0jYvUxO9KwHYrUna9GxK8DQvcpW1K5HwLcjQtexG9LYnQ5D8LQnUpO1C5PwjcrQlO5C0D4vUjetC1O5DUrYnWxO9CwPYjUta1G5K0jG1G5L0DYvUhe9KxH4LUjYtWxO8DwvYrWlK9GwL8jQvehG9L4HQrclS9OwHe1C9OwD8vQne5G1L4PQjcvS1O5D0LYnUpe1CxP4jUva1G5K1DQvUjW9L0vUhe9KxH4rUnatGxK8DwvcjWlK5GwL8jQvexC9LwHUrclS9OxD8rQncoO8LQncrG1K5HwDcvQlO5C0L4nUrc1CxO4DUvYnW5O1C4PUjcta1G5L0jY9G4LUnYvWxK9DwPcjUlK5GxL8nQvchC9KxHwrcnS9OxC8LQncrW1C5OwDO1K5PwDcvSlO5C0L4nUrelCxO4DUvYnW5K0D4PUjUtaxG4L0HYvWhe9CwHUjK9CxP4jUvYlGxK8HwvcjW9KxH4LUnQvexC9LwHcrUlK5GxD8vQncpD0vQje5C1L4nUrclC5O9D0vYnU5K1C4P0jcvaxG5L0HYvUja9CxP8DUnYoH8D0vapWxL8HwPcjStKxH8L8HQtehC8LwH8rWla5GwD8PQnepS1L4H0Lc5K4H0rcnQpO5C0PYnUra1C5O0DcvYnW5K1H4vUjYtCxO4L0nYvWhK9CwPKxK9HwvcjStKxG8L0nYrexC9KwHcrUna5GxL8PQncrC1K5H0LcnQpO5C0LSpexD8P4nUralC5P0D8vQhepK1H4P0jatSxO9D0PYrWha9DwP8DUvahHwjUvaxG9K0nQvcjS9KxH8rUnYpWxK9PwncrS1K5G0L8nQve5C1P4HUrYnD4nUralG5O0DcvQjW5K1G4PUjYtSxO9D0nYrUhK9GxP8jUvahG9K8HwrcwP4H0J6NyB+MD0P4F2J6F2IP8DwN6B2IKEH4P0B6N6AH8L0H6J2B6MHwP7/xAAWEQEBAQAAAAAAAAAAAAAAAAARAFD/2gAIAQMBAT8QZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZna//8QAGREBAQADAQAAAAAAAAAAAAAAETAgcICQ/9oACAECAQE/EORWrpJq4MX0ddPtXln/xAAZEAEBAQEBAQAAAAAAAAAAAAARABBAIDD/2gAIAQEAAT8QIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIiIiIiIjCIwiIiIiIiIiIiIiIiIiIiIiIiIiIiNIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIwwiIiIiIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjSIiIiIiIiIiIiIiIjCIiIiIiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIiIiIiIwiIiIiIjSIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiMIiIiMIiIiIiIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiMIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIjCIiIjCIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIjCIiIjCIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIwwiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjSIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIiIiIjDCIiIiIiIiIiIiIwiIiIwiMIiIiIiIiIiIiIiIiIiIiIiIiIiIjSIiIiIiIiIiIiIiIiIiIiI0iIiIiIiMIiIiIiIjCIiIiIiIiIiIiIwiIiIwiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIjCIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIwiIiIwiIiIiIiIiIiIiIiIiIiIiIwiIiIiIiMIiIiIiIiIiIiIjCIiIjCI0iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjCIiIjCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIwiIiIiIiIiMIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIwiIiIjjPodJzHeeC//2Q=="

TINY = (40, 40)          # 低于 600px 下限：用来验证「分辨率过低」仍会被提出
TINY_RGB = (110, 110, 110)


def jpeg(name):
    """取合成 JPEG 字节。name: cover.jpg / fig.jpg"""
    return base64.b64decode(_COVER_B64 if name == "cover.jpg" else _FIG_B64)


def png(w, h, rgb=TINY_RGB):
    """纯标准库拼一张最小合法 PNG（zlib + CRC），不引第三方依赖。"""
    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    row = b"\x00" + bytes(rgb) * w
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(row * h, 9)) + chunk(b"IEND", b""))


# ---- 五篇合成稿：覆盖回归需要的结构，不覆盖文笔 ----
# 每篇的 baseline 是「机器可验证」的落点：人格、图片数、是否有 peak、目录、首屏层数。
# 改渲染器不该动这张表；这张表动了，说明解析或首屏推导变了——那必须是有意的。
# 注意：语料由本文件合成，所以这张表锁的是解析与推导，不再声称锁住某批真实文章的编辑判断。
CORPUS = {
    # 纯文字：无图、无封面，验证只有文字与列表时结构仍成立。
    "skills": {
        "baseline": {"theme": "paper", "imgs": 0, "peak": True, "toc": False, "layers": 1},
        "md": """---
title: 合成用例|可复用的判断
theme: paper
density: standard
author: 回归作者
bio: 合成回归语料，不含事实主张
cta: 这是回归用的合成文本，请勿引用。
---

> 【合成回归语料】本文只用于验证渲染链，不主张任何事实，也不代表任何机构或行业。

## 为什么要有回归

回归要回答的是确定性问题：**同样的稿子，渲染出来是不是同一份正文。** 这类问题适合交给机器守住。

- 结构：标题、段落、列表、表格、代码是否按预期成形。
- 资产：图片与封面是否被找到、被嵌入、被声明职责。
- 字段：标题、作者、摘要是否落到平台原生字段，正文不再重印。

## 哪些不该被冻结

==审美不属于机器判断。== 字号、留白与节奏由通读的人决定，回归只报告可确定的缺陷。
`render.py` 输出预览与 meta，判断仍然在人这一侧。

::: peak
回归的价值，是把已经修好的缺陷变成不会再回来的护栏。
:::

::: note 说明
本用例为合成文本；出现的数字与说法均为演示，非统计结果。
:::
""",
    },
    # letter + 一张场景图 + 引文：验证图片职责、引文出处与叙事语气。
    "portrait": {
        "baseline": {"theme": "letter", "imgs": 1, "peak": True, "toc": False, "layers": 1},
        "md": """---
title: 合成用例|一个人的十九年
theme: letter
density: standard
date: 2026年10月8日
cover: images/cover.jpg
author: 回归作者
bio: 合成回归语料，不含事实主张
cta: 合成文本，请勿引用。
---

> 【合成虚构叙事】老周在这条线上走了十九年。问他意义，他想了很久，说：就是把电送过去。

## 一天走十二公里

山路没有捷径。他每天检查同一批标记，记下同一类异常，然后把记录交给下一个人。

![合成示意图：巡线场景](images/fig.jpg "场景")

> 重复不是浪费，重复让下一个人不必重新学一遍。
> —— 合成引文，非真实采访

## 交接的难点

难的不是体力，是把只存在于经验里的判断写下来。写下来以后，接班的人才能在他不在的时候做同样的决定。

::: peak
把经验变成可以交接的记录，比多走一趟更重要。
:::
""",
    },
    # frost + 副题 + bars + 证据图 + 表格：验证最容易失真的一段——数据、口径与来源。
    "visual": {
        # layers=1：只有 deck 落在第一段之前（本篇开篇是正文段，不是导语）。
        "baseline": {"theme": "frost", "imgs": 1, "peak": True, "toc": False, "layers": 1},
        "md": """---
title: 合成用例|交付也写在时间表里
theme: frost
density: airy
deck: 一张演示用的时间表
date: 2026年10月8日
cover: images/cover.jpg
author: 回归作者
bio: 合成回归语料，不含事实主张
cta: 合成文本，请勿引用。
source: https://example.com/synthetic-case
---

合成语料同样要验证最难的一段：**证据、图表与来源能不能对上。**

## 数字必须就近给口径

::: bars 兆瓦（演示）
10｜甲情景
35｜乙情景
:::

::: note 假设演示，非统计
两情景为合成假设，不代表任何机构实测；示例来源：https://example.com/synthetic-data
:::

![合成示意图：交付时序](images/fig.jpg "证据")

::: note 来源与口径
合成演示数据，非实测：https://example.com/synthetic-data；期间为演示期间。
:::

| 项目 | 口径 | 状态 |
|---|---|---|
| 甲 | 演示值 | 未核 |
| 乙 | 演示值 | 未核 |

::: peak
没有口径的数字不是证据，只是装饰。
:::
""",
    },
    # folio + dense + cover: todo + data：验证待补封面路径与 data 原语。
    "brief": {
        "baseline": {"theme": "folio", "imgs": 0, "peak": True, "toc": False, "layers": 1},
        "md": """---
title: 合成用例|风险藏在合同里
theme: folio
density: dense
date: 2026年10月8日
cover: todo
author: 回归作者
bio: 合成回归语料，不含事实主张
cta: 合成文本，请勿引用。
---

> 合成语料也要覆盖没有素材的稿子：只有文字与表格时，结构仍然要站得住。

## 三种口径

风险不由名词决定，而由合同承诺什么决定。下面只用演示值说明怎么读。

| 维度 | 甲 | 乙 |
|---|---|---|
| 计量对象 | 演示 | 演示 |
| 需要核对 | 演示 | 演示 |

## 一个演示指标

::: data
125%｜甲情景（演示）
92%｜乙情景（演示）
:::

::: note 演示计算
以下为演示值，非统计结果：期初均为 100，期末分别为 125 与 92；留存率＝期末÷期初×100%。不代表任何厂商或行业。
:::

::: peak
换计量单位之前，先把口径写清楚。
:::
""",
    },
    # paper + toc + 3 个 H2 + 代码：验证目录位置与代码围栏。
    "longread": {
        "baseline": {"theme": "paper", "imgs": 0, "peak": True, "toc": True, "layers": 1},
        "md": """---
title: 合成用例|好系统往往很无聊
theme: paper
density: standard
date: 2026年10月8日
toc: true
cover: images/cover.jpg
author: 回归作者
bio: 合成回归语料，不含事实主张
cta: 合成文本，请勿引用。
---

> 对基础设施来说，成绩往往不显眼：不是让人惊叹，而是不让故障进入日常。

## 第一层：可观测

先能看见，才谈得上改。最小的一组指标是延迟、错误与饱和度。

```bash
# 合成示例：只演示渲染，不是可运行脚本
watch -n 5 'echo demo'
```

## 第二层：可回滚

改动能撤回，判断才有空间。回滚路径要在动手之前写好。

## 第三层：可交接

记录写给下一个人。术语、边界与已知风险都要写清楚。

::: peak
可靠性不是英雄主义，是把无聊的事做完整。
:::
""",
    },
}

CASES = tuple(CORPUS)


def build(dest):
    """在 dest 里生成整套回归输入：5 篇合成稿 + 封面/正文图 + 过小图。返回 dest。"""
    for sub in ("images", "fixtures"):
        os.makedirs(os.path.join(dest, sub), exist_ok=True)
    for name, spec in CORPUS.items():
        with open(os.path.join(dest, name + ".md"), "w", encoding="utf-8") as f:
            f.write(spec["md"])
    for rel, blob in (("images/cover.jpg", jpeg("cover.jpg")),
                      ("images/fig.jpg", jpeg("fig.jpg")),
                      ("fixtures/tiny.png", png(*TINY))):
        with open(os.path.join(dest, rel.replace("/", os.sep)), "wb") as f:
            f.write(blob)
    return dest


if __name__ == "__main__":
    import sys
    import tempfile
    d = build(sys.argv[1] if len(sys.argv) > 1 else tempfile.mkdtemp(prefix="wechat-fixtures-"))
    print(d)
